changelog-seen = 2
[llvm]
link-shared = true

[build]
docs = false
build = "x86_64-unknown-linux-musl"
host = [ "x86_64-unknown-linux-musl" ]
target = [ "x86_64-unknown-linux-musl" ]
tools = [ "analysis", "cargo", "clippy", "src", "rustfmt" ]
submodules = false
vendor = true
extended = true
python = "python3"

[install]
prefix = "@prefix@"
libdir = "@libdir@"
docdir = "@docsdir@"
mandir = "share/man"

[rust]
channel = "stable"
rpath = true
codegen-tests = false
ignore-git = true
optimize = true
codegen-units = 0
llvm-libunwind = "no"
description = "Dragora GNU/Linux-Libre"

[target.x86_64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
sanitizers = false
crt-static = false
