changelog-seen = 2
[llvm]
ccache = "/usr/bin/ccache"
link-shared = true

[build]
docs = false
build = "x86_64-unknown-linux-musl"
host = [ "x86_64-unknown-linux-musl" ]
target = [ "x86_64-unknown-linux-musl" ]
tools = [ "analysis", "cargo", "clippy", "src", "rustfmt" ]
submodules = false
vendor = true
extended = true
locked-deps = true
python = "python3"

[install]
prefix = "@prefix@"
libdir = "@libdir@"
docdir = "@docsdir@"
mandir = "share/man"

[rust]
channel = "stable"
rpath = false
jemalloc = false
ignore-git = true
optimize = true
debug = false
codegen-tests = false
codegen-units = 1
codegen-units-std = 1
llvm-libunwind = "no"
description = "Dragora GNU/Linux-Libre"

incremental = false
parallel-compiler = false

[target.x86_64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static = false

[dist]
src-tarball = false

